### ISSUE TITLE
В задании просят больше на 10 (а не в)

### ISSUE THREAD

**Issue by DanaZL** [FearGateLP10/lesson1#1]
https://github.com/FearGateLP10/lesson1/blob/ae9326b8a2af29baaed2e64c9ef5ca0b705aba14/number_string.py#L14

**Comment by FearGateLP10** [comment]
fixed

**Comment by FearGateLP10** [comment]
https://github.com/FearGateLP10/lesson1/commit/ed0d94f0fbe6d902288f62c56e2cfef400bdb0f3
