### ISSUE TITLE
Не нашла в коде эту проверку

### ISSUE THREAD

**Issue by DanaZL** [FearGateLP10/lesson1#3]
https://github.com/FearGateLP10/lesson1/blob/ed0d94f0fbe6d902288f62c56e2cfef400bdb0f3/dict.py#L14

**Comment by FearGateLP10** [comment]
fixed

**Comment by FearGateLP10** [comment]
https://github.com/FearGateLP10/lesson1/commit/7c19740e47ba47cf0cd116d2de150f6a8c57ca88
